apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::895543011867:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1JAI54WUU320R
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::895543011867:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-08T15:58:45Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
    manager: vpcLambda
    operation: Update
    time: "2022-03-08T15:58:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1217"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d0537e2c-fda0-4f5b-986a-66a5ce3632ea
