apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::895543011867:role/UdacityFlaskDeployCBKubectlRole
      username: build      
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::895543011867:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-2NVOBFTCZXF0
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-04T21:10:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1402"
  uid: aff00554-505c-48ed-9847-f631fdb92da0
